//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string Organization { get; set; }
        public string Note { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int Serial { get; set; }
        public int Number { get; set; }
        public string Photo { get; set; }
    }
}
